### ISSUE TITLE
Not conencting even though the keys in .env are updated

### ISSUE THREAD

**Issue by ucefooo** [demostanis/42evaluators#11]
so bascially i did everything its asked for but when making it says this error 
i build the dev and everything where could the problem be. for . env i get it from connecting to 42 intra and from dev tool cookies : _intra_42_session_production and user.id so i am stuck here i dont know what the problem is...

**Comment by demostanis** [comment]
be careful with posting ur debug prints here lol
see the other issues

**Comment by ucefooo** [comment]
lol i forgot, i didnt find a solution on other issues what should i do?
