### ISSUE TITLE
Sql execution problem

### ISSUE THREAD

**Issue by Ropnez** [demostanis/42evaluators#12]
I installed nix in docker and i run devenv up, but postgresql gives an error like the following, when I try to make it, it cannot connect to sql because it does not open, how can I solve this problem

make ;
error opening database: failed to connect to `host=localhost user=root database=`: dial error (dial tcp [::1]:5432: connect: connection refused)

devenv up;
![Screenshot 2024-08-15 at 23 48 55](https://github.com/user-attachments/assets/0c1b8fcd-eaae-4f9c-8e81-489fc4c6e339)

**Comment by demostanis** [comment]
create a separate user in your docker container
