### ISSUE TITLE
RNCP Calculator Question

### ISSUE THREAD

**Issue by DrSocket** [demostanis/42evaluators#7]
Hello, 1-2 months ago I was on 42evaluators and the rncp page directed me to another website to calculate the rncp projects. I've been looking around for it since this closed but haven't found it, I looked around in the repo for the alert or notification I got a couple of months back but haven't found it there either, do any of the maintainers know what I'm talking about and have the url? thank you

**Comment by demostanis** [comment]
https://github.com/demostanis/42evaluators/blob/66313eb982ab872322b0f73f125a3923afbd0a04/web/templates/links.templ#L59
