### ISSUE TITLE
make doesn't finish 

### ISSUE THREAD

**Issue by imranboutadghart** [demostanis/42evaluators#8]
when i try to make, it starts Downloading some dependencies then it stops with "panic: deleted, sorry ;("
here's the full error message i'm getting
`goroutine 1 [running]:
github.com/demostanis/42evaluators/internal/api.(*KeysManager).pullAuthenticityToken(...)
        /home/kali/42evaluators/internal/api/keys.go:147
github.com/demostanis/42evaluators/internal/api.NewKeysManager(0xc000253830)
        /home/kali/42evaluators/internal/api/keys.go:81 +0x2c7
main.main()
        /home/kali/42evaluators/cmd/main.go:62 +0x306
exit status 2
make: *** [Makefile:14: dev] Error 1
`

**Comment by demostanis** [comment]
yes, i deleted automatic API key generation
