### ISSUE TITLE
Can't make it work...

### ISSUE THREAD

**Issue by vK-1337** [demostanis/42evaluators#9]
Hello, i tried to follow instructions but im blocked at :

env  go run  cmd/*.go
panic: deleted, sorry ;(

goroutine 1 [running]:
github.com/demostanis/42evaluators/internal/api.(*KeysManager).pullAuthenticityToken(...)
	/Users/vk/Documents/42/42evaluators/internal/api/keys.go:147
github.com/demostanis/42evaluators/internal/api.NewKeysManager(0x140002cb830)
	/Users/vk/Documents/42/42evaluators/internal/api/keys.go:81 +0x24c
main.main()
	/Users/vk/Documents/42/42evaluators/cmd/main.go:62 +0x2b4
exit status 2
make: *** [Makefile:14: dev] Error 1

Pretty sure I created the .env with the right informations from intra's Storage.

**Comment by demostanis** [comment]
#8
